name: Protectium
version: '1.0.0'
description: "Protecciones basadas en cubos. Solo existen mientras el bloque esté colocado."
api-version: '1.21'
main: com.protectium.core.ProtectiumPlugin
author: Protectium

commands:
  prot:
    description: "Comando raíz de Protectium."
    usage: "/prot <subcomando> [argumentos]"
    permission: protectium.admin
    aliases: [protectium, proteger]

permissions:
  protectium.admin:
    description: "Acceso administrativo completo."
    default: op
  protectium.bypass:
    description: "Inmune a todas las protecciones activas."
    default: op
  protectium.place:
    description: "Permite colocar protecciones."
    default: true
  protectium.unlimited:
    description: "Sin límite de protecciones."
    default: op
  protectium.limit.vip:
    description: "15 protecciones máx, radio 48."
    default: false
  protectium.limit.vipplus:
    description: "20 protecciones máx, radio 64."
    default: false
  protectium.limit.mvp:
    description: "30 protecciones máx, radio 96."
    default: false
  protectium.limit.mvpplus:
    description: "50 protecciones máx, radio 128."
    default: false
